# Generated by Django 4.1.5 on 2024-03-14 08:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0031_alter_review_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="user",
        ),
    ]
