# Generated by Django 4.1.5 on 2024-04-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0032_remove_review_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryBoy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
