# Generated by Django 4.1.5 on 2024-04-05 03:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0033_deliveryboy"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Review",
        ),
    ]
