# Generated by Django 4.1.5 on 2024-04-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0038_remove_maintenancerequest_equipment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("OUT_FOR_DELIVERY", "Out for Delivery"),
                    ("DELIVERED", "Delivered"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
