# Generated by Django 4.1.5 on 2024-04-15 05:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0039_order_delivery_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="delivery_status",
        ),
    ]
